### ISSUE TITLE
[Bug] CombatManager / _longDefense 삭제 이슈

### ISSUE THREAD

**Issue by JJARSANGKIM** [Gongju-Unity-Bootcamp/UNHOLY-Justice#113]
# 테스트 환경
- OS : Window11
- CPU : i7-1165G7
- GPU : GTX 1650ti
- Mode : Editor

# 설명
- Git 충돌 및 branch 이슈로 이전에 생성하였던 CombatManager.cs 내 _longDefense 필드 값이 사라졌습니다.

# 재현하기
1. 작성 중이던 브랜치의 이슈가 꽤 오래전 이슈였습니다.
2. 해당 이슈를 커밋하고 푸쉬하는 과정에서 충돌 발생했습니다.
3. 충돌을 해결하고 머지하는 과정에서 관련된 메소드가 몇 개 사라지는 현상이 발생했습니다.
4. 그 결과 _longDefense가 없어지는 현상이 발생하였습니다.

# 스크린샷
- editor 상 오류 화면
![image](https://github.com/Gongju-Unity-Bootcamp/UNHOLY-Justice/assets/102023674/300df4dc-9205-4a79-a0fb-46c319448b4f)
- 오류가 난 script 부분
![image](https://github.com/Gongju-Unity-Bootcamp/UNHOLY-Justice/assets/102023674/0d997778-6893-44aa-9156-630462c75fcb)
MinoController.cs

**Comment by 2gangmin** [comment]
이외 특수 공격 관련 스크립트 메소드 및 오브젝트(postion) 등 모두 증발. 이전 브랜치로 해결할 예정
