### ISSUE TITLE
[기획] 원거리 무기 FSM 설계

### ISSUE THREAD

**Issue by Hinnlang** [Gongju-Unity-Bootcamp/UNHOLY-Justice#15]
# 설명
원거리 무기 활(Bow)에 대한 FSM을 설계합니다.
[원거리 fsm](https://app.diagrams.net/#G1BohwlsinYhebZYlRqoT8bgfZnj5hIooN#%7B%22pageId%22%3A%22kS7KWmBxPf0OWDB5LeJT%22%7D)

![원거리 fsm](https://github.com/Gongju-Unity-Bootcamp/UNHOLY-Justice/assets/84132454/45a34b0c-ebf8-401d-872a-f19028e42326)

# 참고자료
- [활 조준 시 조준점 생성(젤다의 전설)](https://youtu.be/CQf38X-K4qU?si=WspHxyCfUs2IMhcO&t=79)
- [몬스터 타켓팅 시 자동으로 조준(엘든링)](https://youtu.be/M7CWA_JZCXU?si=KnJrS6ib7DkZs4W_&t=60)

# 주의사항
- 원거리 무기는 근거리 무기와 상태가 다릅니다.
   - 공격 모션은 다음과 같이 두 단계로 나뉩니다.
      - 조준(Aming)
  ![Bow_Aming](https://github.com/Gongju-Unity-Bootcamp/UNHOLY-Justice/assets/84132454/7e472c57-32e9-436f-b6a5-816422167536)
     - 발사(Fire)
![Bow_Fire](https://github.com/Gongju-Unity-Bootcamp/UNHOLY-Justice/assets/84132454/98b8668b-cb5a-43ae-af5f-857b7a7487fa)
      - 콤보 공격이 없습니다. 
      - 점프 공격이 없습니다.
      - 달리기 공격이 없습니다.
      - 패링이 없습니다.
   - 방어(Defense)가 없습니다.

**Comment by Hinnlang** [comment]
팀원의 리뷰가 필요합니다.

**Comment by 2gangmin** [comment]
확인했습니다 :)

**Comment by JJARSANGKIM** [comment]
확인했습니다:D
