### ISSUE TITLE
[Docs] 몬스터(Boss) 시스템 설계 정리 

### ISSUE THREAD

**Issue by 2gangmin** [Gongju-Unity-Bootcamp/UNHOLY-Justice#16]
# 설명
몬스터(Boss) 시스템 설계된 문서를 정리 및 보완한다.

# 참고자료
- [몬스터(보스) 기획](https://docs.google.com/document/d/1_GgT7GC1FsJaZqIh5gnu111742SsoGSqkawW3DPll1I/edit)

# 주의사항
Behavior Tree 를 사용하여 설계한다.

**Comment by ChoiSeonMun** [comment]
BT로 정리할 것

**Comment by 2gangmin** [comment]
BT 로 설계 완료.
