### ISSUE TITLE
[Feat] 전투시스템

### ISSUE THREAD

**Issue by JJARSANGKIM** [Gongju-Unity-Bootcamp/UNHOLY-Justice#19]
# 설명
전투시스템 기획, 설계 문서 작성
- 전투돌입 전, 후의 구성.
- 전투시 피격, 타격판정, 데미지의 수치화.
- 전투 종료 후의 구성.
- 
# 참고자료
관련된 기획서 혹은 이슈 등의 링크를 답니다.
- [엘든링 보스방 돌입시](https://www.youtube.com/watch?v=GGVnqkT5LSY)
- [문서2](링크)
- [문서3](링크)

# 주의사항

**Comment by ChoiSeonMun** [comment]
public class ParringBehaviour : StateMachineBehaviour
{
    public float StartTime = 0.5f;
    public float EndTime = 0.7f;
    
    private MinoController;


    OnUpdate()
    {
        MinoController.CanParrying = false;

        if (stateInfo.normalizedTime이 StartTime과 EndTime 사이일 때)
        {
            MinoController.CanParrying = true;
        }
    }
    
    
}

class MinoController
{
    public void Parrying()
    {
        if (CanParrying == false)
        {
            return;
        }

        Parring 애니메이션 플레이
        기절 적용
        CanParrying = false;
    }
}


class Player
{
    void Parring()
    {
        MinoController controller;

        controller.Parrying();
    }
}
