### ISSUE TITLE
[기획] Player 시스템 기획 

### ISSUE THREAD

**Issue by Hinnlang** [Gongju-Unity-Bootcamp/UNHOLY-Justice#21]
# 설명
- player system에 대한 전반적인 규칙을 정합니다.
- player fsm을 설계합니다.
- [플레이어 기획](https://docs.google.com/presentation/d/1Buc7ra-_VSmfL4jAkmyLJMv3u_pz9jzVRMRuatfnGzw/edit#slide=id.g26922897fec_0_8)

# 참고자료
- [플레이어 시스템](https://docs.google.com/presentation/d/1Buc7ra-_VSmfL4jAkmyLJMv3u_pz9jzVRMRuatfnGzw/edit#slide=id.g28ec7b3cbef_0_53)

# 주의사항

**Comment by Hinnlang** [comment]
- 수정 사항
   - Player 시스템 계획에는 각 무기의 전체적인 fsm을 정리해놓았습니다.
   - 각 무기에 대한 상세한 fsm은 무기 시스템으로 분류하였습니다.
   - player의 공통적인 상태에 대한 fsm을 정리하였습니다.
   - upper body fsm에 대한 설명은 추가할 생각입니다.
- 모든 팀원의 리뷰 부탁드립니다.

**Comment by 2gangmin** [comment]
확인했습니다.
플레이어 기획 ppt 안에 수정이 필요한 부분 댓글 추가했으니 확인바랍니다.

**Comment by Hinnlang** [comment]
수정했습니다. 한번 더 확인 해주세요

**Comment by 2gangmin** [comment]
확인했습니다.

**Comment by JJARSANGKIM** [comment]
확인했습니다~
