### ISSUE TITLE
[기획] 무기 시스템 기획

### ISSUE THREAD

**Issue by Hinnlang** [Gongju-Unity-Bootcamp/UNHOLY-Justice#22]
# 설명
- 근거리 무기와 원거리 무기의 fsm을 설계합니다.
- 근거리 무기 간의 애니메이션 교체를 설계합니다.
- 근거리 무기와 원거리 무기 간의 교체 조건을 기획합니다.
- [무기 시스템](https://docs.google.com/presentation/d/1Oje2IJLyWDr_Sn9QAQWdLFGjEguTV5cFTi23_mgr__o/edit#slide=id.g28ec7b3cbef_0_53)

# 참고자료
관련된 기획서 혹은 이슈 등의 링크를 답니다.
- [Sub-State Machine](https://docs.unity3d.com/kr/560/Manual/NestedStateMachines.html)
- [Animation Layer](https://docs.unity3d.com/kr/560/Manual/AnimationLayers.html)
- [Blend tree](https://docs.unity3d.com/kr/560/Manual/class-BlendTree.html)
- [Animator Override controller](https://docs.unity3d.com/kr/560/Manual/AnimatorOverrideController.html)

# 주의사항

**Comment by DO0OG** [comment]
- 수정 사항
   - 각 무기에 대한 FSM과 하위에 속해있는 하위 상태 머신 FSM에 대해 기술해 놓았습니다.
- 모든 팀원의 리뷰 부탁드립니다.

**Comment by 2gangmin** [comment]
무기 시스템 ppt 안에 수정할 내용들을 댓글로 남겼으니 수정 후 댓글 남겨주세요.

**Comment by DO0OG** [comment]
- 수정 사항
   - 피드백 사항 수정하였습니다.
- 모든 팀원의 리뷰 부탁드립니다.

**Comment by 2gangmin** [comment]
수정 사항 확인했습니다.
