### ISSUE TITLE
[Feat] Input system setting (key binding & inspector 창 설정)

### ISSUE THREAD

**Issue by Hinnlang** [Gongju-Unity-Bootcamp/UNHOLY-Justice#25]
# 설명
- 플레이어 Input System을 세팅합니다.
   - 기본적인 key binding을 설정합니다.
   - inspector 창을 설정합니다.
   - Input System을 실험해보기 위한 간단한 이동 코드를 작성합니다.
  
-------------------------------------------------------
- Input System Key Binding
![Image](https://github.com/Gongju-Unity-Bootcamp/UNHOLY-Justice/assets/84132454/aadecb74-e67c-4bc2-aaae-bbcf36348efe)
- inspector 창 설정
![Image](https://github.com/Gongju-Unity-Bootcamp/UNHOLY-Justice/assets/84132454/d7c665bb-a77e-4d98-b84c-f5dda661c8a9)

- 이동 키를 누르면 player의 y 값이 1.08로 고정되는 이슈 발생
   - 해결: charactercontroller로 간단한  이동을 구현하다가 발생한 이슈였음. 대신 rigidbody를 이용한 움직임을 구현함 

# 참고자료
관련된 기획서 혹은 이슈 등의 링크를 답니다.
- [Input System](https://docs.unity3d.com/Packages/com.unity.inputsystem@1.7/manual/index.html)
- [Unity Manual(Blend Tree)](https://docs.unity3d.com/Manual/class-BlendTree.html)
- [Player 기획서](https://docs.google.com/presentation/d/1Buc7ra-_VSmfL4jAkmyLJMv3u_pz9jzVRMRuatfnGzw/edit#slide=id.g2b8b263d5bb_0_10)
- [Unity EldenRing](https://www.youtube.com/watch?v=Xg6GvHpWjaE&list=PLD_vBJjpCwJvP9F9CeDRiLs08a3ldTpW5&index=3)

# 주의사항
- 플레이어의 스테미너는 고려하지 않습니다.

**Comment by Hinnlang** [comment]
- 변경 사항

**Comment by 2gangmin** [comment]
확인했습니다.
