### ISSUE TITLE
[Feat] Monster (boss) BT 기능 구현

### ISSUE THREAD

**Issue by JJARSANGKIM** [Gongju-Unity-Bootcamp/UNHOLY-Justice#27]
# 설명
- 몬스터(보스)의 Behavior Tree의 'BossNomalAttack1', 'BossTrack' 구현
- 현재 Action Node 'BossIdle'과 'BossDie' 까지만 구현됨
![image](https://github.com/Gongju-Unity-Bootcamp/UNHOLY-Justice/assets/102023674/eedc88df-fb91-4b54-8cb8-3a32c9fbf4f0)

# 참고자료
관련된 기획서 혹은 이슈 등의 링크를 답니다.
- [몬스터(보스)BT](https://app.diagrams.net/#G1HDJk2RFC2-wKXkjYoqsEVOYq4A2R-OZx)
- [Unity BT 참고](https://leekangw.github.io/posts/91/)
- [Unity BT 노드 데이터 구조화](https://github.com/YB970902/EternalSmash/tree/main/Assets/Scripts/Character/BehaviourTree)
- [2D Game Kit- BT 구현 참고](https://assetstore.unity.com/packages/templates/tutorials/2d-game-kit-107098#content)

# 주의사항
기능을 개발할 때 주의사항에 대해서 작성합니다.

**Comment by JJARSANGKIM** [comment]
-[BT 구조 수정](https://github.com/orgs/Gongju-Unity-Bootcamp/projects/25/views/1?pane=issue&itemId=53403950)

**Comment by 2gangmin** [comment]
변경된 구조로 인해 이슈를 닫음.
