### ISSUE TITLE
[Docs] 몬스터(보스) Behavior Tree 수정사항

### ISSUE THREAD

**Issue by JJARSANGKIM** [Gongju-Unity-Bootcamp/UNHOLY-Justice#41]
# 설명
- ![image](https://github.com/Gongju-Unity-Bootcamp/UNHOLY-Justice/assets/102023674/00f567b8-ecca-44aa-998b-04062fb19930)
- Track 액션 노드를 Attack 노드 뒤로 변경함 : Attack 범위 내 플레이어 감지 시 Attack state가 먼저 재생되어야함.
- Attack 노드 구현시 Selector(무작위) NodeState 내부에 조건식 Condition은 맞지 않다는 피드백을 받아 수정함.
- 애니메이션 state중 백점프 후 발구르기 각각 두개의 애니메이션을 sequence 순차적으로 재생되게 수정함.

# 참고자료
관련된 기획서 혹은 이슈 등의 링크를 답니다.

# 주의사항
기능을 개발할 때 주의사항에 대해서 작성합니다.

**Comment by 2gangmin** [comment]
보스 페이즈에 따른 트리구조가 변경이 생길 수 있어 충분한 회의를 통해 결정할 예정.

**Comment by Hinnlang** [comment]
확인했습니다.

**Comment by DO0OG** [comment]
확인했습니다.
