### ISSUE TITLE
[Feat] Monster (boss) 애니메이션 스크립팅

### ISSUE THREAD

**Issue by JJARSANGKIM** [Gongju-Unity-Bootcamp/UNHOLY-Justice#44]
# 설명
- 몬스터(보스) 동작시 Animation.CrossFade를 사용하여 다음 동작이 자연스럽게 이어지게함.

# 참고자료
관련된 기획서 혹은 이슈 등의 링크를 답니다.
- [Animation.CrossFade 스트립팅](https://docs.unity3d.com/kr/530/ScriptReference/Animation.html)

# 주의사항

**Comment by Hinnlang** [comment]
- Animation.CrossFade 사용 안 하기로 함
