### ISSUE TITLE
[R&D] Moster(boss) behavior tree

### ISSUE THREAD

**Issue by 2gangmin** [Gongju-Unity-Bootcamp/UNHOLY-Justice#45]
# 설명
변경된 behavior tree 구조에 따라 개발에 들어갈 때 필요한 내용들을 공부한다.

# 참고자료
관련된 기획서 혹은 이슈 등의 링크를 답니다.
- [Unity Asset Store 2D Game Kit](https://assetstore.unity.com/packages/templates/tutorials/2d-game-kit-107098#content)
- [Github BT](https://github.com/YB970902/EternalSmash/tree/main/Assets/Scripts/Character/BehaviourTree)
- [Github fluid BT](https://github.com/ashblue/fluid-behavior-tree?tab=readme-ov-file)
- #41 

# 주의사항
기능을 개발할 때 주의사항에 대해서 작성합니다.

**Comment by Hinnlang** [comment]
- behaviour tree 생성 완료
