### ISSUE TITLE
[Bug] Jump - Dodge animation 전환 오류

### ISSUE THREAD

**Issue by Hinnlang** [Gongju-Unity-Bootcamp/UNHOLY-Justice#52]
# 설명
1. Jump 키와 Dodge 키 순서대로 바로 눌렀을 때
![02_19_jumpdodge_error2](https://github.com/Gongju-Unity-Bootcamp/UNHOLY-Justice/assets/84132454/d47bb78d-4c33-419f-8536-5105d817a2c8)

2. Dodge 키와 Jump 키 순서대로 바로 눌렀을 때
 ![02_19_jumpdodge_error1](https://github.com/Gongju-Unity-Bootcamp/UNHOLY-Justice/assets/84132454/e9ec5ff1-24a5-4407-b250-60b741c2b898)

- Jump와 Dodge는 모두 trigger로 전환이 되고 그 값들이 키가 눌림과 동시에 전환이 되어서 일어나는 버그입니다.
- Dodge animation 도중에 animation이 재생되고 있음을 추적하고 그 값을 근거로 jump가 작동되지 않도록 프로그램을 구성했으나, transition이 되는 순간에 jump가 가능한 문제가 있었습니다.
- jump animation이 실행되는 도중 dodge가 불가능하도록 막아야 합니다.
 
# 참고자료
관련된 기획서 혹은 이슈 등의 링크를 답니다.
- #48 
- #49 

# 주의사항

**Comment by DO0OG** [comment]
- 수정사항
   - 카메라의 위치를 임의적으로 변경하였습니다.
   - 변경된 카메라 위치는 본 게임에는 반영되지 않습니다.
