### ISSUE TITLE
[Feat] Monster(boss) Behavior Tree Build

### ISSUE THREAD

**Issue by JJARSANGKIM** [Gongju-Unity-Bootcamp/UNHOLY-Justice#53]
# 설명
- Fluid BT를 이용하여 몬스터 BT를 구성함.
![image](https://github.com/Gongju-Unity-Bootcamp/UNHOLY-Justice/assets/102023674/7bd737c8-00b1-44aa-bcc4-af77b257a13b)

# 참고자료
관련된 기획서 혹은 이슈 등의 링크를 답니다.
- [Fluid Behavior Tree - Example](https://github.com/ashblue/fluid-behavior-tree-ctf-example/tree/master)
- [Github fluid BT](https://github.com/ashblue/fluid-behavior-tree?tab=readme-ov-file)
- #45 

# 주의사항
기능을 개발할 때 주의사항에 대해서 작성합니다.

**Comment by 2gangmin** [comment]
#62 
리빌드 완료
