### ISSUE TITLE
[R&D] Level Design

### ISSUE THREAD

**Issue by JJARSANGKIM** [Gongju-Unity-Bootcamp/UNHOLY-Justice#78]
# 설명
게임 내 레벨 디자인.
- 플레이어 대기영역, 전투영역 구성
- 맵 구성 에셋

# 참고자료

# 주의사항
기능을 개발할 때 주의사항에 대해서 작성합니다.

**Comment by Hinnlang** [comment]
- 레벨 추가 완료
