### ISSUE TITLE
[Feat] Sound 추가

### ISSUE THREAD

**Issue by JJARSANGKIM** [Gongju-Unity-Bootcamp/UNHOLY-Justice#80]
# 설명
- 게임에 필요한 음악을 추가합니다.
- 각 상태에 알맞는 음악을 재생할 수 있도록 합니다.

# 필요한 음악
- 타이틀 화면 
- 버튼 클릭 음
- 대기 중(비 전투 상태)
- 전투 시작(전투 상태)
- 죽음
   - 죽는 소리 
   - 게임 오버 음악
- 이김
   - 게임 클리어 소리
   - 보스 죽는 소리  
- 타격
   - 금속 부딪히는 소리
   - 땅 부딪히는 소리
   - 땅의 잔해물이 비산하는 소리
   - 발 구르기 소리
- 피격
   - 방어 시, 금속 부딪히는 소리
   - 피 뿜는 소리
   - ~~플레이어 고통스러운 소리~~
   - ~~스턴 소리~~ 
- 공격
   - 칼, 도끼 휘두르는 소리
- 플레이어
   - 점프 소리 
   - 구르기 소리 
   - 발소리 
- 보스 발소리 

______
### BGM
- [x] title
- [x] in game_room
- [x] in game_boss room

### effect
- [x] 걷기
- [] 뛰기
- [x] 공격
- [x] 패링
- [x] 방어
- [] 방어 깨짐
- [x] 점프
- [x] 회피

# 참고자료
- [엘든링 전사 호라 루 보스전](https://www.youtube.com/watch?v=byz4r7SRyS0&t=408s)
- [엘든링 끔찍한 흉조 멀기트](https://www.youtube.com/watch?v=yeC2wL83Q00)

# 주의사항
- 동시에 재생이 가능한 음악과 그렇지 않은 음악의 구별이 필요합니다.

**Comment by 2gangmin** [comment]
![image](https://github.com/Gongju-Unity-Bootcamp/UNHOLY-Justice/assets/95378064/8aca6c84-940d-4552-a421-7fc269dff1ef)
이렇게 추가 완료.
